# visualization settings

[data]
dataset_folder_path = "../../data/processed/graph_data_nohubs/merged_types/split_dataset/seed_4/"
results_folder_path = "../../data/experiments/merged_types_experiment/"
tensor_df_path = "../../data/processed/graph_data_nohubs/merged_types/split_dataset/seed_4/tensor_df.csv"

[model]
weights_path = "../../data/experiments/merged_types_experiment/sage_ones_first_negatives_exp_04_07_23__12_07.pth"
model_type = "sage_ones"
supervision_types = ["gda"]
feature_type = "ones"
feature_dim = 10

[misc]
seed = 0
save_plot_data = true
plot_title = "Negative sampling experiment"
model_name = "negative_sampling_experiment"