# visualization settings

[data]
dataset_folder_path = "../../data/processed/graph_data_nohubs/merged_types/split_dataset/seed_4/"
results_folder_path = "../../data/experiments/merged_types_experiment/"
tensor_df_path = "../../data/processed/graph_data_nohubs/merged_types/split_dataset/seed_4/tensor_df.csv"

[model]
weights_path = "../../data/experiments/merged_types_experiment/bootstrap_exp/sage_ones_new_ratio_11_07_23__15_46.pth"
model_type = "sage_ones"
supervision_types = ["gda"]
feature_type = "lsa"
feature_dim = 10

[misc]
seed = 4
save_plot_data = true
plot_title = "LSA_vector experiment"
model_name = "LSA_vector_experiment"